# Generated by Django 4.2.1 on 2023-05-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_knowledgebase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebase",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="media/knowledge_base/"
            ),
        ),
    ]
