# Generated by Django 4.2.1 on 2023-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_alter_knowledgebase_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                    ("Sent", "Sent"),
                    ("Rejected", "Rejected"),
                    ("Blocked", "Blocked"),
                ],
                max_length=15,
            ),
        ),
    ]
