# Generated by Django 4.2.1 on 2023-05-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0004_alter_ticket_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
